import { useCallback, useState } from 'react'
import { Alert, FlatList, Modal, RefreshControl, Text, TextInput, TouchableOpacity, useWindowDimensions, View } from 'react-native'
import { useFocusEffect, useNavigation } from '@react-navigation/native'
import { ImportEbookButton } from '../components/ImportEbookButton'
import { ActionButton } from '../components/ActionButton'
import { AppHeader } from '../components/AppHeader'
import { BookCover } from '../components/BookCover'
import { EmptyState } from '../components/EmptyState'
import { LoadingState } from '../components/LoadingState'
import { useFamily } from '../context/FamilyContext'
import { apiClient } from '../lib/api'
import type { Book } from '../lib/types'
import { colors } from '../theme/colors'
import { spacing } from '../theme/spacing'
import { typography } from '../theme/typography'
function asList<T>(value: T[] | { results: T[] }) { return Array.isArray(value) ? value : value.results }
export function CatalogScreen() {
  const navigation = useNavigation<any>(); const { familyId } = useFamily(); const { width } = useWindowDimensions()
  const [books, setBooks] = useState<Book[]>([]); const [query, setQuery] = useState(''); const [ordering, setOrdering] = useState('-created_at'); const [selected, setSelected] = useState<number[]>([]); const [selecting, setSelecting] = useState(false); const [importOpen, setImportOpen] = useState(false); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { if (!familyId) { setLoading(false); return } const params = new URLSearchParams({ ordering }); if (query.trim()) params.set('search', query.trim()); setBooks(asList(await apiClient.get<Book[] | { results: Book[] }>(`/books/?${params.toString()}`))) }, [familyId, ordering, query])
  useFocusEffect(useCallback(() => { const timer = setTimeout(() => { void load().catch(() => setError('藏书暂时无法加载。')).finally(() => setLoading(false)) }, 180); return () => clearTimeout(timer) }, [load]))
  const toggle = (id: number) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); const leaveSelection = () => { setSelecting(false); setSelected([]) }
  const bulkDelete = () => Alert.alert('删除所选书籍？', `将删除 ${selected.length} 本书及其副本。`, [{ text: '取消', style: 'cancel' }, { text: '删除', style: 'destructive', onPress: () => void Promise.all(selected.map((id) => apiClient.delete(`/books/${id}/`))).then(() => { leaveSelection(); return load() }).catch(() => setError('部分书籍删除失败，请重试。')) }])
  const bulkCategory = () => Alert.prompt('批量归类', '请输入分类名称', async (category) => { if (!category?.trim()) return; try { await Promise.all(selected.map((id) => apiClient.patch(`/books/${id}/`, { category: category.trim() }))); leaveSelection(); await load() } catch { setError('归类失败，请重试。') } })
  const itemWidth = Math.max(44, (width - spacing.lg * 2 - spacing.sm * 5) / 6)
  if (loading && !books.length) return <LoadingState label="正在翻找藏书" />
  return <View style={{ backgroundColor: colors.paper, flex: 1, padding: spacing.lg }}>{selecting ? <View style={{ alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.xl }}><TouchableOpacity onPress={() => setSelected(selected.length === books.length ? [] : books.map((book) => book.id))}><Text style={{ color: colors.terracotta, fontFamily: typography.body, fontSize: 15 }}>{selected.length === books.length ? '取消全选' : '全选'}</Text></TouchableOpacity><Text style={{ color: colors.ink, fontFamily: typography.display, fontSize: 24 }}>选择书籍</Text><TouchableOpacity onPress={leaveSelection}><Text style={{ color: colors.muted, fontFamily: typography.body, fontSize: 15 }}>取消</Text></TouchableOpacity></View> : <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}><AppHeader subtitle={`${books.length} 个书名`} title="藏书" /><View style={{ flexDirection: 'row', gap: 12, marginTop: 7 }}><TouchableOpacity onPress={() => setImportOpen(true)}><Text style={{ color: colors.terracotta }}>导入</Text></TouchableOpacity><TouchableOpacity onPress={() => setSelecting(true)}><Text style={{ color: colors.ink }}>选择</Text></TouchableOpacity></View></View>}
    {!selecting && <><TextInput accessibilityLabel="搜索藏书" onChangeText={setQuery} placeholder="搜索书名、作者或分类" placeholderTextColor={colors.muted} style={{ backgroundColor: colors.paperBright, borderColor: colors.line, borderRadius: 10, borderWidth: 1, color: colors.ink, height: 50, marginBottom: spacing.sm, paddingHorizontal: 15 }} /><View style={{ flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.md }}><Text style={{ color: colors.muted, fontSize: 10, paddingVertical: 10 }}>排序</Text>{[['-created_at', '最近添加'], ['title', '书名'], ['category', '分类'], ['-updated_at', '最近更新']].map(([value, label]) => <TouchableOpacity key={value} onPress={() => setOrdering(value)} style={{ backgroundColor: ordering === value ? colors.ink : colors.paperBright, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 8 }}><Text style={{ color: ordering === value ? colors.white : colors.muted, fontSize: 10 }}>{label}</Text></TouchableOpacity>)}</View></>}
    {error ? <Text style={{ color: colors.danger, marginBottom: spacing.md }}>{error}</Text> : null}<FlatList columnWrapperStyle={{ gap: spacing.sm }} contentContainerStyle={{ gap: spacing.md, paddingBottom: selecting ? 180 : 120 }} data={books} initialNumToRender={24} keyExtractor={(item) => String(item.id)} maxToRenderPerBatch={30} numColumns={6} refreshControl={<RefreshControl colors={[colors.terracotta]} onRefresh={() => { setRefreshing(true); void load().finally(() => setRefreshing(false)) }} refreshing={refreshing} />} renderItem={({ item }) => <TouchableOpacity accessibilityRole="button" onPress={() => selecting ? toggle(item.id) : navigation.navigate('BookDetail', { bookId: item.id })} style={{ width: itemWidth }}><View><BookCover category={item.category} coverUrl={item.cover_url || item.cover} seed={item.id} small title={item.title} />{selecting && <View style={{ alignItems: 'center', backgroundColor: selected.includes(item.id) ? colors.terracotta : 'rgba(255,255,255,.9)', borderRadius: 12, bottom: 5, height: 24, justifyContent: 'center', position: 'absolute', right: 5, width: 24 }}><Text>{selected.includes(item.id) ? '✓' : '○'}</Text></View>}</View><Text numberOfLines={2} style={{ color: colors.ink, fontSize: 10, lineHeight: 13, marginTop: 5 }}>{item.title}</Text></TouchableOpacity>} ListEmptyComponent={<EmptyState title="书架还是空的" copy="点击右上角导入第一本书。" />} />
    {selecting && <View style={{ backgroundColor: colors.paperBright, borderTopColor: colors.line, borderTopWidth: 1, bottom: 0, flexDirection: 'row', gap: 6, left: 0, padding: spacing.md, paddingBottom: 92, position: 'absolute', right: 0 }}><ActionButton disabled={!selected.length} onPress={bulkDelete} quiet>删除</ActionButton><ActionButton disabled={!selected.length} onPress={() => Alert.alert('阅读状态', '电子书阅读状态请进入详情管理。')} quiet>已读/未读</ActionButton><ActionButton disabled={!selected.length} onPress={bulkCategory} quiet>归类</ActionButton></View>}
    <Modal animationType="fade" transparent visible={importOpen} onRequestClose={() => setImportOpen(false)}><TouchableOpacity onPress={() => setImportOpen(false)} style={{ backgroundColor: 'rgba(0,0,0,.35)', flex: 1, justifyContent: 'flex-end' }}><View style={{ backgroundColor: colors.paperBright, borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: spacing.xl }}><Text style={{ color: colors.ink, fontFamily: typography.display, fontSize: 25 }}>导入书籍</Text><ActionButton onPress={() => { setImportOpen(false); navigation.navigate('AddBook') }}>扫码/拍照添加实体书</ActionButton><ActionButton onPress={() => { setImportOpen(false); navigation.navigate('AddBook') }} quiet>手动添加实体书</ActionButton><View style={{ marginTop: 8 }}><ImportEbookButton /></View></View></TouchableOpacity></Modal>
  </View>
}
