import { useCallback, useEffect, useState } from 'react'
import { FlatList, RefreshControl, Text, TouchableOpacity, View } from 'react-native'

import { AppHeader } from '../components/AppHeader'
import { EmptyState } from '../components/EmptyState'
import { ErrorState } from '../components/ErrorState'
import { LoadingState } from '../components/LoadingState'
import { useFamily } from '../context/FamilyContext'
import { apiClient } from '../lib/api'
import type { Notification } from '../lib/types'
import { colors } from '../theme/colors'
import { spacing } from '../theme/spacing'
import { typography } from '../theme/typography'

function asList<T>(value: T[] | { results: T[] }) { return Array.isArray(value) ? value : value.results }
export function NotificationsScreen() { const { familyId } = useFamily(); const [items, setItems] = useState<Notification[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(''); const load = useCallback(async () => { if (familyId) setItems(asList(await apiClient.get<Notification[] | { results: Notification[] }>('/notifications/'))) }, [familyId]); useEffect(() => { void load().catch(() => setError('通知暂时无法加载。')).finally(() => setLoading(false)) }, [load]); async function markRead(id: number) { const updated = await apiClient.post<Notification>(`/notifications/${id}/mark-read/`); setItems((current) => current.map((item) => item.id === id ? updated : item)) } async function markAll() { await apiClient.post('/notifications/mark-all-read/'); setItems((current) => current.map((item) => ({ ...item, is_read: true }))) } if (loading) return <LoadingState label="正在收取通知" />; const unread = items.filter((item) => !item.is_read).length; return <View style={{ backgroundColor: colors.paper, flex: 1, padding: spacing.lg }}><AppHeader subtitle={`${unread} 条未读`} title="通知" />{error ? <ErrorState message={error} onRetry={() => { setError(''); void load() }} /> : <FlatList contentContainerStyle={{ gap: spacing.sm, paddingBottom: 120 }} data={items} keyExtractor={(item) => String(item.id)} refreshControl={<RefreshControl colors={[colors.terracotta]} onRefresh={() => { setRefreshing(true); void load().finally(() => setRefreshing(false)) }} refreshing={refreshing} />} ListHeaderComponent={unread ? <TouchableOpacity onPress={() => void markAll()} style={{ marginBottom: spacing.sm }}><Text style={{ color: colors.terracotta, fontFamily: typography.mono, fontSize: 10 }}>全部标为已读 →</Text></TouchableOpacity> : null} renderItem={({ item }) => <TouchableOpacity disabled={item.is_read} onPress={() => void markRead(item.id)} style={{ backgroundColor: item.is_read ? colors.paperBright : '#F2D4C4', borderRadius: 14, padding: spacing.lg }}><Text style={{ color: colors.terracotta, fontFamily: typography.mono, fontSize: 10, letterSpacing: 1, textTransform: 'uppercase' }}>{item.notification_type}</Text><Text style={{ color: colors.ink, fontFamily: typography.body, fontSize: 16, fontWeight: '600', marginTop: 10 }}>{item.title}</Text><Text style={{ color: colors.muted, fontFamily: typography.body, fontSize: 13, lineHeight: 19, marginTop: 6 }}>{item.content}</Text><Text style={{ color: colors.muted, fontFamily: typography.mono, fontSize: 9, marginTop: 12 }}>{new Date(item.created_at).toLocaleString('zh-CN')}</Text></TouchableOpacity>} ListEmptyComponent={<EmptyState title="现在没有新消息" copy="借阅到期和预约变化会在这里提醒你。" />} />}</View> }
