import { useEffect, useState } from 'react'
import { ScrollView, Text, View } from 'react-native'

import { AppHeader } from '../components/AppHeader'
import { BookCover } from '../components/BookCover'
import { EmptyState } from '../components/EmptyState'
import { LoadingState } from '../components/LoadingState'
import { useFamily } from '../context/FamilyContext'
import { apiClient } from '../lib/api'
import type { AnnualReport, Recommendation } from '../lib/types'
import { colors } from '../theme/colors'
import { spacing } from '../theme/spacing'
import { typography } from '../theme/typography'

export function ReportsScreen() { const { familyId } = useFamily(); const [report, setReport] = useState<AnnualReport | null>(null); const [books, setBooks] = useState<Recommendation[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!familyId) return; Promise.all([apiClient.get<AnnualReport>(`/reports/annual/?year=${new Date().getFullYear()}`), apiClient.get<{ books: Recommendation[] }>('/reports/recommendations/')]).then(([nextReport, nextBooks]) => { setReport(nextReport); setBooks(nextBooks.books) }).finally(() => setLoading(false)) }, [familyId]); if (loading) return <LoadingState label="正在写下阅读记录" />; return <ScrollView contentContainerStyle={{ padding: spacing.lg, paddingBottom: 120 }} style={{ backgroundColor: colors.paper }}><AppHeader subtitle={`${report?.year || new Date().getFullYear()} 年`} title="阅读报告" /><View style={{ backgroundColor: colors.ink, borderRadius: 16, padding: spacing.xl }}><Text style={{ color: colors.terracottaLight, fontFamily: typography.mono, fontSize: 10, letterSpacing: 1 }}>这一年借过</Text><Text style={{ color: colors.white, fontFamily: typography.display, fontSize: 62, letterSpacing: -3, marginTop: 25 }}>{report?.total_loans ?? '—'}</Text><Text style={{ color: 'rgba(255,255,255,.62)', fontFamily: typography.body, fontSize: 13 }}>次借阅动作</Text></View><Text style={{ color: colors.ink, fontFamily: typography.display, fontSize: 25, marginTop: spacing.xxl }}>每月借阅</Text><View style={{ backgroundColor: colors.paperBright, borderRadius: 16, flexDirection: 'row', height: 190, justifyContent: 'space-around', marginTop: spacing.md, padding: spacing.lg, paddingTop: 30 }}>{(report?.monthly_distribution || []).map((item) => { const max = Math.max(...(report?.monthly_distribution || []).map((entry) => entry.count), 1); return <View key={item.month} style={{ alignItems: 'center', justifyContent: 'flex-end' }}><View style={{ backgroundColor: colors.terracotta, borderRadius: 5, height: Math.max(5, item.count / max * 120), width: 8 }} /><Text style={{ color: colors.muted, fontFamily: typography.mono, fontSize: 8, marginTop: 8 }}>{item.month}</Text></View>})}</View><Text style={{ color: colors.ink, fontFamily: typography.display, fontSize: 25, marginTop: spacing.xxl }}>推荐给下一次阅读</Text>{books.length ? <View style={{ flexDirection: 'row', gap: spacing.md, marginTop: spacing.md }}>{books.slice(0, 2).map((book) => <View key={book.id} style={{ flex: 1 }}><BookCover category={book.category} seed={book.id} small title={book.title} /><Text numberOfLines={2} style={{ color: colors.ink, fontFamily: typography.body, fontSize: 13, marginTop: 7 }}>{book.title}</Text></View>)}</View> : <EmptyState title="还没有推荐" copy="完成几次借阅后，这里会出现个性化推荐。" />}</ScrollView> }
