import { useState } from 'react'
import { Modal, Text, TextInput, TouchableOpacity, View } from 'react-native'
import type { Membership } from '../lib/types'
import { ActionButton } from './ActionButton'
import { colors } from '../theme/colors'

export function CheckoutSheet({ visible, members, busy, onClose, onSubmit }: { visible: boolean; members: Membership[]; busy?: boolean; onClose: () => void; onSubmit: (borrowerId: number, dueAt: string) => void }) {
  const [selected, setSelected] = useState<number | null>(null); const [date, setDate] = useState('')
  const borrower = selected || members[0]?.user
  return <Modal animationType="slide" transparent visible={visible} onRequestClose={onClose}><View style={{ backgroundColor: 'rgba(0,0,0,.35)', flex: 1, justifyContent: 'flex-end' }}><View style={{ backgroundColor: colors.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24 }}><Text style={{ color: colors.ink, fontSize: 26, fontWeight: '700' }}>借出实体书</Text><Text style={{ color: colors.muted, marginTop: 8 }}>选择借阅人</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }}>{members.filter((m) => m.is_active).map((m) => <TouchableOpacity key={m.id} onPress={() => setSelected(m.user)} style={{ backgroundColor: borrower === m.user ? colors.ink : colors.paperBright, borderColor: colors.line, borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 9 }}><Text style={{ color: borrower === m.user ? colors.white : colors.ink }}>{m.user_detail.nickname || m.user_detail.username}</Text></TouchableOpacity>)}</View><Text style={{ color: colors.muted, marginTop: 18 }}>归还日期（YYYY-MM-DD）</Text><TextInput value={date} onChangeText={setDate} keyboardType="numbers-and-punctuation" placeholder="例如 2026-10-08" style={{ backgroundColor: colors.paperBright, borderRadius: 10, color: colors.ink, marginTop: 8, padding: 12 }} /><View style={{ flexDirection: 'row', gap: 10, marginTop: 20 }}><View style={{ flex: 1 }}><ActionButton onPress={onClose} quiet>取消</ActionButton></View><View style={{ flex: 1 }}><ActionButton disabled={!borrower || !date.trim()} loading={busy} onPress={() => borrower && onSubmit(borrower, new Date(`${date}T23:59:59`).toISOString())}>确认借出</ActionButton></View></View></View></View></Modal>
}
