/* eslint-disable react-hooks/purity */
import { useState } from 'react'
import { Modal, Text, TouchableOpacity, View } from 'react-native'
import DateTimePicker from '@react-native-community/datetimepicker'
import type { Membership } from '../lib/types'
import { ActionButton } from './ActionButton'
import { colors } from '../theme/colors'

export function CheckoutSheet({ visible, members, busy, onClose, onSubmit }: { visible: boolean; members: Membership[]; busy?: boolean; onClose: () => void; onSubmit: (borrowerId: number, dueAt: string) => void }) {
  const [selected, setSelected] = useState<number | null>(null); const [date, setDate] = useState(() => new Date(Date.now() + 86400000)); const borrower = selected || members[0]?.user; const formatted = date.toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'short' })
  return <Modal animationType="slide" transparent visible={visible} onRequestClose={onClose}><View style={{ backgroundColor: 'rgba(0,0,0,.35)', flex: 1, justifyContent: 'flex-end' }}><View style={{ backgroundColor: colors.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 24 }}><Text style={{ color: colors.ink, fontSize: 26, fontWeight: '700' }}>借出纸质书</Text><Text style={{ color: colors.muted, marginTop: 8 }}>选择借阅人</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 }}>{members.filter((m) => m.is_active).map((m) => <TouchableOpacity key={m.id} onPress={() => setSelected(m.user)} style={{ backgroundColor: borrower === m.user ? colors.ink : colors.paperBright, borderColor: colors.line, borderRadius: 18, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 9 }}><Text style={{ color: borrower === m.user ? colors.white : colors.ink }}>{m.user_detail.nickname || m.user_detail.username}</Text></TouchableOpacity>)}</View><Text style={{ color: colors.muted, marginTop: 18 }}>归还日期</Text><View style={{ alignItems: 'center', backgroundColor: colors.paperBright, borderRadius: 12, marginTop: 8, paddingVertical: 4 }}><DateTimePicker display="inline" locale="zh-CN" minimumDate={new Date(Date.now() + 86400000)} mode="date" onChange={(_, value) => value && setDate(value)} value={date} /></View><Text style={{ color: colors.ink, textAlign: 'center', marginTop: 4 }}>{formatted}</Text><View style={{ flexDirection: 'row', gap: 10, marginTop: 20 }}><View style={{ flex: 1 }}><ActionButton onPress={onClose} quiet>取消</ActionButton></View><View style={{ flex: 1 }}><ActionButton disabled={!borrower} loading={busy} onPress={() => borrower && onSubmit(borrower, new Date(date.setHours(23, 59, 59, 0)).toISOString())}>确认借出</ActionButton></View></View></View></View></Modal>
}
